### PR TITLE
Task_A

### PR DESCRIPTION
**Pull request by hamza-sadruddin**
Waiting for review.

### CODE REVIEW

**Comment by sdam12** [comment]
In Makefile, there is no command for creating bin and build directory on runtine. Please include command for creation.
Following is the sample command for your reference.
bin_directroy := $(shell mkdir -p bin).

**Comment by hamza-sadruddin** [comment]
> In Makefile, there is no command for creating bin and build directory on runtine. Please include command for creation

Thank you for your feedback. I will integrate it.

**Review by khanyousefzai — DISMISSED** [review]
I have modified the makefile as per required review. Please have a look at it again. Thanks.

**Comment by nick7695** [comment]
Makefile and structure of the folder looks fine.

**Review by sdam12 — APPROVED** [review]
Re-Structuring of Folder and Single Make File for the project looks good after implementing changes the changes requested.

**Review by nick7695 — APPROVED** [review]

**Pull request merged**
